name: Node.js CI

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Asia/Shanghai"
    - uses: actions/checkout@v4.2.2
    - name: Use Node.js
      uses: actions/setup-node@v4.1.0
      with:
        cache: 'npm'
    - run: npm install
    - run: node main.js
    - name: Git Commit/Push Changes
      uses: EndBug/add-and-commit@v9
      with:
        add: ./vrp.ics
